//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K94Warriors.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogProfile
    {
        public DogProfile()
        {
            this.DogMedicalRecords = new HashSet<DogMedicalRecord>();
            this.DogNotes = new HashSet<DogNote>();
            this.DogSkills = new HashSet<DogSkill>();
            this.MetaDatas = new HashSet<MetaData>();
        }
    
        public int ProfileID { get; set; }
        public string Name { get; set; }
        public string Breed { get; set; }
        public Nullable<int> Age { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> PickedUpDate { get; set; }
        public Nullable<int> DonorID { get; set; }
        public bool IsFixed { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public Nullable<int> WarriorID { get; set; }
    
        public virtual ICollection<DogMedicalRecord> DogMedicalRecords { get; set; }
        public virtual ICollection<DogNote> DogNotes { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual WarriorInfo WarriorInfo { get; set; }
        public virtual ICollection<DogSkill> DogSkills { get; set; }
        public virtual ICollection<MetaData> MetaDatas { get; set; }
    }
}
