//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K94Warriors.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogSkillName
    {
        public DogSkillName()
        {
            this.DogSkills = new HashSet<DogSkill>();
        }
    
        public string SkillName { get; set; }
    
        public virtual ICollection<DogSkill> DogSkills { get; set; }
    }
}
