//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K94Warriors.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class k94warriors_dbEntities : DbContext
    {
        public k94warriors_dbEntities()
            : base("name=k94warriors_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DogEvent> DogEvents { get; set; }
        public DbSet<DogMedicalRecord> DogMedicalRecords { get; set; }
        public DbSet<DogNote> DogNotes { get; set; }
        public DbSet<DogProfile> DogProfiles { get; set; }
        public DbSet<DogSkillName> DogSkillNames { get; set; }
        public DbSet<DogSkill> DogSkills { get; set; }
        public DbSet<Donor> Donors { get; set; }
        public DbSet<MetaData> MetaDatas { get; set; }
        public DbSet<WarriorInfo> WarriorInfoes { get; set; }
    }
}
