//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K94Warriors.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaData
    {
        public int MetaDataID { get; set; }
        public string MetaKey { get; set; }
        public string MetaValue { get; set; }
        public Nullable<int> DonorID { get; set; }
        public Nullable<int> WarriorID { get; set; }
        public Nullable<int> DogProfileID { get; set; }
        public Nullable<int> DogEventID { get; set; }
        public Nullable<int> DogNoteID { get; set; }
        public Nullable<int> MedicalRecordID { get; set; }
    
        public virtual DogEvent DogEvent { get; set; }
        public virtual DogMedicalRecord DogMedicalRecord { get; set; }
        public virtual DogNote DogNote { get; set; }
        public virtual DogProfile DogProfile { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual WarriorInfo WarriorInfo { get; set; }
    }
}
