//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K94Warriros.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogEvent
    {
        public int EventID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime EventDate { get; set; }
        public int DogProfileID { get; set; }
        public int EventTypeId { get; set; }
    
        public virtual DogProfile DogProfile { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
