//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K94Warriros.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DogNote
    {
        public int NoteID { get; set; }
        public int DogProfileID { get; set; }
        public string Note { get; set; }
        public bool IsCritical { get; set; }
        public int NoteTypeId { get; set; }
    
        public virtual DogProfile DogProfile { get; set; }
        public virtual NoteType NoteType { get; set; }
    }
}
