// <auto-generated />
namespace K94Warriors.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class ChangedAgeToBirthYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedAgeToBirthYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201309191636031_ChangedAgeToBirthYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
