// <auto-generated />
namespace K94Warriors.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NoteAttachmentFileExtension : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoteAttachmentFileExtension));
        
        string IMigrationMetadata.Id
        {
            get { return "201310171935539_NoteAttachmentFileExtension"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
