// <auto-generated />
namespace K94Warriors.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DogImages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DogImages));
        
        string IMigrationMetadata.Id
        {
            get { return "201309191538278_DogImages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
