// <auto-generated />
namespace K94Warriors.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TaskTypesAndEmailRecipients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskTypesAndEmailRecipients));
        
        string IMigrationMetadata.Id
        {
            get { return "201310292250202_TaskTypesAndEmailRecipients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
