// <auto-generated />
namespace K94Warriors.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DogMedications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DogMedications));
        
        string IMigrationMetadata.Id
        {
            get { return "201309262129546_DogMedications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
