// <auto-generated />
namespace K94Warriors.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddNoteAttachments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNoteAttachments));
        
        string IMigrationMetadata.Id
        {
            get { return "201309262223500_AddNoteAttachments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
